services:
  # The webshop is our java application that uses tomcat to serve jsp files
  webshop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URI: jdbc:postgresql://db:5432/webshop
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cdn
    restart: unless-stopped

  # The db is our database that we use in our application
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: webshop
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dbdata:
  cdn_dbdata:
